import { test, after } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { renderStatus, renderDecisionIndex } from "../scripts/harness-status.mjs";
import { makeRepo, cleanup, status, task, decision } from "./helpers/fixture.mjs";

after(cleanup);

test("an empty repo renders a status that says so, not an empty table", () => {
  const out = renderStatus(makeRepo({ config: { project: "empty-thing" } }));
  assert.match(out, /# Status — empty-thing/);
  assert.match(out, /Harness `0\.2\.0` · profile `solo`/);
  assert.match(out, /No tasks yet\./);
  assert.match(out, /Nothing open\. Plan the next task/);
  assert.match(out, /None\. All decisions are accepted or superseded\./);
  assert.match(out, /Empty\./);
});

test("tasks are grouped in state order, not filename order", () => {
  const out = renderStatus(makeRepo({
    tasks: {
      "T-001-a.md": task({ id: "T-001", status: "done" }),
      "T-002-b.md": task({ id: "T-002", status: "ready" }),
      "T-003-c.md": task({ id: "T-003", status: "doing" }),
    },
  }));
  const order = [...out.matchAll(/\| \[(T-\d+)\]/g)].map((m) => m[1]);
  assert.deepEqual(order, ["T-002", "T-003", "T-001"], "ready, then doing, then done");
});

test("Next prefers doing over review over blocked over ready, and ignores done", () => {
  const pick = (states) => renderStatus(makeRepo({
    tasks: Object.fromEntries(states.map((s, i) => [`T-00${i + 1}-x.md`, task({ id: `T-00${i + 1}`, status: s })])),
  })).match(/\*\*(T-\d+)\*\*/)?.[1];

  assert.equal(pick(["ready", "blocked", "review", "doing"]), "T-004");
  assert.equal(pick(["ready", "blocked", "review"]), "T-003");
  assert.equal(pick(["ready", "blocked"]), "T-002");
  assert.equal(pick(["done", "superseded"]), undefined, "closed tasks are not 'next'");
});

test("only proposed decisions are listed as open", () => {
  const out = renderStatus(makeRepo({
    decisions: {
      "D-001-a.md": decision({ id: "D-001", state: "accepted" }),
      "D-002-b.md": decision({ id: "D-002", state: "proposed" }),
    },
  }));
  assert.match(out, /- D-002 — Fixture decision — `proposed`, needs human approval/);
  assert.doesNotMatch(out, /D-001/);
});

test("the journal shows the last five entries, newest first", () => {
  const lines = Array.from({ length: 7 }, (_, i) => `2026-08-2${i} | T-00${i} | done | outcome ${i} | 1 file | ok | -`);
  const out = renderStatus(makeRepo({ journal: lines.join("\n") }));
  const shown = [...out.matchAll(/^- (2026-08-2\d) \|/gm)].map((m) => m[1]);
  assert.deepEqual(shown, ["2026-08-26", "2026-08-25", "2026-08-24", "2026-08-23", "2026-08-22"]);
});

test("the decision index strips the ID prefix from titles and marks an empty set", () => {
  assert.match(renderDecisionIndex(makeRepo()), /\| — \| — \| No decisions recorded yet \| — \| — \|/);

  const row = renderDecisionIndex(makeRepo({
    decisions: { "D-004-x.md": decision({ id: "D-004", supersedes: "D-002" }) },
  }));
  assert.match(row, /\| \[D-004\]\(D-004-x\.md\) \| 2026-08-26 \| Fixture decision \| `accepted` \| D-002 \|/);
});

test("generation is deterministic: a second run writes nothing", () => {
  const root = makeRepo({ tasks: { "T-001-a.md": task() }, decisions: { "D-001-a.md": decision() } });
  const first = readFileSync(join(root, "STATUS.md"), "utf8");

  const second = status(root);
  assert.equal(second.code, 0);
  assert.match(second.stdout, /up to date/);
  assert.equal(readFileSync(join(root, "STATUS.md"), "utf8"), first);
});

test("generated files carry the do-not-edit banner", () => {
  const root = makeRepo();
  for (const path of ["STATUS.md", "docs/decisions/README.md"]) {
    assert.match(readFileSync(join(root, path), "utf8"), /^<!-- Generated by scripts\/harness-status\.mjs\. Do not edit by hand\. -->/);
  }
});
