#!/usr/bin/env node
/**
 * Regenerates STATUS.md and docs/decisions/README.md from the repo's own records.
 * Deterministic: no timestamps, no ordering by mtime. Running it twice produces no diff.
 * Never hand-edit the files it writes.
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { ROOT, config, tasks, decisions, journal, isEntrypoint, OPEN_STATES, TASK_STATES } from "./lib/harness.mjs";

const JOURNAL_TAIL = 5;
const BANNER = "<!-- Generated by scripts/harness-status.mjs. Do not edit by hand. -->";

export function renderStatus(root = ROOT) {
  const cfg = config(root);
  const all = tasks(root);
  const open = all.filter((t) => OPEN_STATES.includes(t.meta?.status));
  const recent = journal(root).slice(-JOURNAL_TAIL).reverse();
  const undecided = decisions(root).filter((d) => d.status === "proposed");

  const out = [BANNER, "", `# Status — ${cfg.project}`, ""];
  out.push(`Harness \`${cfg.harness}\` · profile \`${cfg.profile}\``, "");

  out.push("## Tasks", "");
  if (all.length === 0) {
    out.push("No tasks yet. Create one from `docs/sdd/TEMPLATES.md` in `docs/tasks/`.", "");
  } else {
    out.push("| Task | State | Goal |", "|---|---|---|");
    for (const state of TASK_STATES) {
      for (const t of all.filter((x) => x.meta?.status === state)) {
        out.push(`| [${t.meta.id}](docs/tasks/${t.name}) | \`${state}\` | ${t.meta.goal ?? "-"} |`);
      }
    }
    out.push("");
  }

  out.push("## Next", "");
  const next = open.find((t) => t.meta.status === "doing") ?? open.find((t) => t.meta.status === "review")
    ?? open.find((t) => t.meta.status === "blocked") ?? open.find((t) => t.meta.status === "ready");
  out.push(
    next
      ? `**${next.meta.id}** (\`${next.meta.status}\`) — ${next.meta.goal ?? next.meta.title}`
      : "Nothing open. Plan the next task before implementing anything.",
    "",
  );

  out.push("## Open decisions", "");
  out.push(
    undecided.length
      ? undecided.map((d) => `- ${d.title} — \`proposed\`, needs human approval`).join("\n")
      : "None. All decisions are accepted or superseded.",
    "",
  );

  out.push(`## Journal — last ${JOURNAL_TAIL}`, "");
  out.push(recent.length ? recent.map((e) => `- ${e.line}`).join("\n") : "Empty.", "");
  out.push("Full history: [`JOURNAL.md`](JOURNAL.md) · decisions: [`docs/decisions/`](docs/decisions/README.md)");
  return `${out.join("\n")}\n`;
}

export function renderDecisionIndex(root = ROOT) {
  const rows = decisions(root).map(
    (d) => `| [${d.id}](${d.name}) | ${d.date} | ${d.title.replace(/^D-\d{3}\s*—\s*/, "")} | \`${d.status}\` | ${d.supersedes} |`,
  );
  return [
    BANNER,
    "",
    "# Decisions",
    "",
    "One file per decision, capped at 40 lines, immutable once accepted — supersede with a new file",
    "rather than editing. Template in `../sdd/TEMPLATES.md`.",
    "",
    "| ID | Date | Title | Status | Supersedes |",
    "|---|---|---|---|---|",
    ...(rows.length ? rows : ["| — | — | No decisions recorded yet | — | — |"]),
    "",
  ].join("\n");
}

function write(path, contents) {
  const previous = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (previous === contents) return false;
  writeFileSync(path, contents);
  return true;
}

if (isEntrypoint(import.meta.url)) {
  const changed = [
    write(join(ROOT, "STATUS.md"), renderStatus()),
    write(join(ROOT, "docs/decisions/README.md"), renderDecisionIndex()),
  ].filter(Boolean).length;
  console.log(changed ? `harness-status: regenerated ${changed} file(s)` : "harness-status: up to date");
}
